#!/usr/bin/env python3
#   ____ _                   _     _         _   _ _____ _____
#  / ___| |__   ___  ___ ___| |__ (_) __ _  | \ | | ____|_   _|
# | |   | '_ \ / _ \/ __/ __| '_ \| |/ _` | |  \| |  _|   | |
# | |___| | | |  __/ (_| (__| | | | | (_| |_| |\  | |___  | |
#  \____|_| |_|\___|\___\___|_| |_|_|\__,_(_)_| \_|_____| |_|
#
#
import os, configparser
from motor.motor_asyncio import AsyncIOMotorClient
from fastapi import FastAPI

config = configparser.ConfigParser()
config.read(".env")
ENV = config['ENV']
APPKEY = config['APPKEY']
SECRETS = config['SECRETS']

app = FastAPI()

# Configurações do MongoDB
MONGO_DB_URL = "mongodb://localhost:27017"
MONGO_DB_NAME = "sua_base_de_dados"

# Conectar ao MongoDB
mongo_client = AsyncIOMotorClient(MONGO_DB_URL)
db = mongo_client[MONGO_DB_NAME]

# Função para iniciar o banco de dados
async def initiate_database():
    # Lógica para iniciar o banco de dados, se necessário
    pass

